// 한글 제목 → 읽을 수 있는 폴더 이름(슬러그).
//
// GCS 경로가 ASCII 만 허용해 예전엔 한글 이름이 통째로 버려지고 projects1771052244218 같은
// 일련번호 폴더가 생겼다(2026-09-24). 국어의 로마자 표기법(음운 변화 규칙 없이 자모 그대로)으로
// 옮겨 "추석" → "chuseok", "모양새 친구들" → "moyangsae-chingudeul" 처럼 사람이 읽는 이름을 만든다.
// 브라우저(prototype/js/service/project.js)에도 같은 표와 함수가 복사돼 있다 — 패리티 테스트가 지킨다.

// ── ROMANIZE_START (브라우저 복사본과 동일해야 함) ──
const HANGUL_INITIALS = ["g", "kk", "n", "d", "tt", "r", "m", "b", "pp", "s", "ss", "", "j", "jj", "ch", "k", "t", "p", "h"];
const HANGUL_MEDIALS = ["a", "ae", "ya", "yae", "eo", "e", "yeo", "ye", "o", "wa", "wae", "oe", "yo", "u", "wo", "we", "wi", "yu", "eu", "ui", "i"];
const HANGUL_FINALS = ["", "k", "k", "k", "n", "n", "n", "t", "l", "k", "m", "l", "l", "l", "p", "l", "m", "p", "p", "t", "t", "ng", "t", "t", "k", "t", "p", "t"];

/** 한글 음절을 로마자로. 한글이 아닌 글자는 그대로 둔다. */
function romanizeHangul(text) {
  var out = "";
  var s = String(text || "");
  for (var i = 0; i < s.length; i++) {
    var code = s.charCodeAt(i);
    if (code < 0xac00 || code > 0xd7a3) { out += s[i]; continue; }
    var idx = code - 0xac00;
    var ini = Math.floor(idx / 588);
    var med = Math.floor((idx % 588) / 28);
    var fin = idx % 28;
    out += HANGUL_INITIALS[ini] + HANGUL_MEDIALS[med] + HANGUL_FINALS[fin];
  }
  return out;
}

/** 제목 → 폴더 슬러그(소문자 영문·숫자·하이픈, 최대 max 자). 쓸 글자가 없으면 "". */
function toSlug(text, max) {
  var limit = Number(max) > 0 ? Number(max) : 40;
  return romanizeHangul(text).toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/-{2,}/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, limit)
    .replace(/-+$/g, "");
}
// ── ROMANIZE_END ──

/** 옛 방식의 자동 생성 id(일련번호). 이런 id 는 새로 만들 때 쓰지 않는다. */
export function isAutoGeneratedProjectId(id) {
  const s = String(id || "").trim();
  return /^projects\d+$/i.test(s) || /^\d+$/.test(s);
}

/** 같은 슬러그가 이미 있으면 -2, -3 … 을 붙인다. */
export function uniqueSlug(base, takenIds) {
  const slug = String(base || "").trim();
  if (!slug) return "";
  const taken = new Set((Array.isArray(takenIds) ? takenIds : []).map((v) => String(v && v.id !== undefined ? v.id : v || "").trim().toLowerCase()).filter(Boolean));
  if (!taken.has(slug.toLowerCase())) return slug;
  for (let i = 2; i < 100; i++) if (!taken.has(`${slug}-${i}`.toLowerCase())) return `${slug}-${i}`;
  return `${slug}-${Date.now().toString(36)}`;
}

export { romanizeHangul, toSlug };
