import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");
const projectSvc = () => read("prototype/js/service/project.js");
const rename = () => read("prototype/functions/api/brand/rename.ts");

test("신규 프로젝트 폴더명은 입력한 이름에서 만든다", () => {
  const src = projectSvc();
  assert.match(src, /function slugifySeriesId\(title, takenIds\)/);
  assert.match(src, /seriesId = seriesId \|\| slugifySeriesId\(seriesTitle, seriesList\) \|\| \('projects' \+ Date\.now\(\)\)/);
  // 같은 이름이 있으면 -2, -3 으로 분리
  assert.match(src, /if \(!taken\[slug \+ '-' \+ i\]\) return slug \+ '-' \+ i/);
});

test("기존 드래프트의 seriesId 폴백은 건드리지 않는다", () => {
  // normalizeDraft 의 폴백을 바꾸면 이미 저장된 프로젝트가 다른 폴더를 가리켜 링크가 끊긴다.
  const src = projectSvc();
  assert.match(src, /var seriesId = normalizeSeriesId\(payload\.seriesId \|\| draft\.seriesId\) \|\| \('projects' \+ id\)/);
  assert.match(read("prototype/js/ui/dashboard.js"), /normalizeSeriesId\(payload\.seriesId \|\| draft\?\.seriesId\) \|\| \('projects' \+ id\)/);
});

test("이름 점검 리포트는 아무것도 바꾸지 않는다", () => {
  const src = rename();
  assert.match(src, /export const onRequestGet/);
  assert.match(src, /dryRun: true/);
  assert.match(src, /function isAutoGeneratedId\(id: string\)/);
  assert.match(src, /\/\^projects\\d\+\$\/i\.test\(id\)/);
  // 리포트에는 현재 이름·제안 id·영향 범위가 함께 나와야 판단할 수 있다
  assert.match(src, /brandTitle/);
  assert.match(src, /suggestedId/);
  assert.match(src, /referencingProjects/);
  // GET 경로에는 쓰기·삭제가 없어야 한다
  const getBlock = src.slice(src.indexOf("export const onRequestGet"), src.indexOf("export const onRequestPost"));
  assert.doesNotMatch(getBlock, /writeJson|copyObject|deleteObject/);
});

test("실제 변경은 확인 없이는 실행되지 않고, 원본을 지우지 않는다", () => {
  const src = rename();
  assert.match(src, /const confirm = String\(body\?\.confirm \|\| ""\)\.trim\(\)\.toLowerCase\(\) === "yes"/);
  assert.match(src, /if \(!confirm\) \{[\s\S]{0,200}dryRun: true, plan/);
  // 삭제는 명시적으로 요청할 때만
  assert.match(src, /const deleteOld = body\?\.deleteOld === true/);
  assert.match(src, /if \(deleteOld\) \{/);
  // 대상 id 가 이미 있으면 덮어쓰지 않는다
  assert.match(src, /이미 있어요\(파일 \$\{existing\.length\}개\)/);
  assert.match(src, /newBrandId 는 영문\/숫자\/\._- 만 사용할 수 있어요/);
});

test("폴더만 옮기지 않고 레코드에 박힌 예전 경로도 고친다", () => {
  const src = rename();
  // 시트 이미지 경로(gs://…/brands/<old>/…)가 브랜드 레코드 안에 들어 있다
  assert.match(src, /JSON\.stringify\(brandRec\)\.split\(oldPrefix\)\.join\(newPrefix\)/);
  assert.match(src, /rewritten\.brandId = newBrandId/);
  // 프로젝트 레코드의 brandId·seriesId·brandRef 도 함께
  assert.match(src, /if \(String\(payload\.brandId \|\| ""\) === brandId\) payload\.brandId = newBrandId/);
  assert.match(src, /if \(String\(payload\.seriesId \|\| ""\) === brandId\) payload\.seriesId = newBrandId/);
  assert.match(src, /payload\.brandRef\.id = newBrandId/);
});

test("프로젝트 이름 입력칸은 한글을 받지 않는다", () => {
  const src = read("prototype/script.js");
  assert.match(src, /project-series-input" placeholder="프로젝트 이름 · 영문/);
  assert.match(src, /replace\(\/\[\^A-Za-z0-9 \._-\]\/g, ''\)/);
  // IME 조합 중에도 남지 않게 input·compositionend 양쪽에서 걸러낸다
  assert.match(src, /seriesInput\.addEventListener\('input', stripNonAscii\)/);
  assert.match(src, /seriesInput\.addEventListener\('compositionend', stripNonAscii\)/);
});

test("id 를 몰라도 현재 이름으로 폴더를 지목할 수 있다", () => {
  const src = rename();
  assert.match(src, /const wantedTitle = String\(body\?\.brandTitle \|\| ""\)\.trim\(\)/);
  assert.match(src, /if \(title && title\.toLowerCase\(\) === wantedTitle\.toLowerCase\(\)\) matches\.push\(id\)/);
  // 같은 이름이 여러 개면 임의로 고르지 않는다
  assert.match(src, /brandId 로 지목해 주세요/);
});
