// 프로젝트 폴더 이름이 일련번호(1771052245118 · projects1771052244218)로 만들어져 무엇인지 알 수 없던 문제(2026-09-24).
// 한글 제목을 로마자 슬러그로 옮겨 "<시리즈>-<에피소드>" 폴더를 만든다. 서버(에이전트)와 브라우저(스튜디오) 둘 다.
import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");
const slug = await import(path.join(root, "prototype/functions/api/_shared/hangul-slug.js").replace(/\\/g, "/").replace(/^([A-Za-z]):/, "file:///$1:"));

test("한글 제목이 읽을 수 있는 로마자 슬러그가 된다", () => {
  assert.equal(slug.romanizeHangul("추석"), "chuseok");
  assert.equal(slug.toSlug("추석"), "chuseok");
  assert.equal(slug.toSlug("모양새 친구들"), "moyangsae-chingudeul");
  assert.equal(slug.toSlug("SHAPES 1화 각성"), "shapes-1hwa-gakseong");
  assert.equal(slug.toSlug("  --  "), "", "쓸 글자가 없으면 빈 문자열");
  assert.equal(slug.toSlug("가".repeat(100), 10).length <= 10, true);
});

test("일련번호 id 는 자동 생성으로 판정하고, 같은 슬러그는 -2, -3 으로 나눈다", () => {
  assert.equal(slug.isAutoGeneratedProjectId("1771052245118"), true);
  assert.equal(slug.isAutoGeneratedProjectId("projects1771052244218"), true);
  assert.equal(slug.isAutoGeneratedProjectId("shapes-chuseok"), false);
  assert.equal(slug.uniqueSlug("shapes-chuseok", ["shapes-chuseok", { id: "shapes-chuseok-2" }]), "shapes-chuseok-3");
  assert.equal(slug.uniqueSlug("shapes-chuseok", []), "shapes-chuseok");
});

test("브라우저 복사본(project.js)의 로마자 표·함수가 서버 모듈과 같다(패리티)", () => {
  const server = read("prototype/functions/api/_shared/hangul-slug.js");
  const browser = read("prototype/js/service/project.js");
  const cut = (src) => src.slice(src.indexOf("// ── ROMANIZE_START"), src.indexOf("// ── ROMANIZE_END ──"));
  const normalize = (s) => s.split("\n").map((l) => l.replace(/^\s+/, "")).join("\n").trim();
  assert.ok(cut(server).length > 200);
  assert.equal(normalize(cut(browser)), normalize(cut(server)));
});

test("에이전트 project_create / project_add_episode 는 절대 일련번호 폴더를 만들지 않는다", () => {
  const shared = read("prototype/functions/api/agent/_shared.ts");
  assert.match(shared, /import \{ toSlug, isAutoGeneratedProjectId, uniqueSlug \} from "\.\.\/_shared\/hangul-slug\.js";/);
  const create = shared.slice(shared.indexOf("async function runProjectCreateTool("), shared.indexOf("\n}\n", shared.indexOf("async function runProjectCreateTool(")));
  assert.match(create, /const readable = !!projectId && \/\^\[a-zA-Z0-9\._-\]\+\$\/\.test\(projectId\) && !isAutoGeneratedProjectId\(projectId\);/);
  assert.match(create, /const base = \[toSlug\(seriesId \|\| seriesTitle, 24\), toSlug\(episodeTitle \|\| input\?\.title \|\| input\?\.name, 24\)\]\.filter\(Boolean\)\.join\("-"\)/);
  assert.match(create, /projectId = uniqueSlug\(base, takenIds\);/);
  assert.match(create, /const seriesId = String\(input\?\.seriesId \|\| ""\)\.trim\(\) \|\| toSlug\(seriesTitle, 40\);/, "시리즈 폴더도 이름에서");
  assert.doesNotMatch(create, /throw new Error\("projectId is required/);
  const add = shared.slice(shared.indexOf("async function runProjectAddEpisodeTool("), shared.indexOf("\n}\n", shared.indexOf("async function runProjectAddEpisodeTool(")));
  assert.match(add, /const seriesSlug = toSlug\(isAutoGeneratedProjectId\(seriesId\) \? seriesTitle : \(seriesId \|\| seriesTitle\), 24\);/);
  assert.match(add, /base = isAutoGeneratedProjectId\(stem\) \? "" : `\$\{stem\}-ep/, "부모가 일련번호면 -ep2 도 쓰지 않는다");
  assert.match(add, /projectId = uniqueSlug\(base, takenIds\);/);
  const orch = read("prototype/functions/api/agent/_orchestrator.ts");
  assert.match(orch, /숫자 일련번호는 절대 쓰지 않는다/);
});

test("스튜디오 화면의 새 에피소드·복제도 이름 기반 폴더를 쓰고, 최신 에피소드 판단이 숫자 id 에 기대지 않는다", () => {
  const src = read("prototype/js/service/project.js");
  assert.match(src, /function episodeIdFor\(seriesId, episodeTitle\)/);
  assert.match(src, /var id = episodeIdFor\(seriesId, episodeTitle\);/);
  assert.match(src, /var newId = episodeIdFor\(source\.seriesId, newTitle\);/);
  assert.match(src, /var slug = romanizeHangul\(String\(title \|\| ''\)\)\.trim\(\)\.toLowerCase\(\)/, "시리즈 슬러그도 한글을 로마자로");
  assert.match(src, /function draftTime\(d\)/);
  assert.doesNotMatch(src, /if \(Number\(d\.id\) > Number\(row\.latestEpisodeId \|\| 0\)\)/);
});

test("일련번호뿐인 옛 프로젝트도 목록에서 주제·첫 컷 제목으로 이름이 붙는다", () => {
  const src = read("prototype/functions/api/agent/production-projects.ts");
  assert.match(src, /const namedSeries = autoId\(seriesTitle\) \? "" : seriesTitle;/);
  assert.match(src, /const title = episodeTitle \|\| namedSeries \|\| text\(payload\.topic \|\| payload\.title\) \|\| text\(scenes\[0\]\?\.title\) \|\| id;/);
});
