// prototype/functions/api/brand/rename.ts
// 브랜드(프로젝트) 폴더 id 점검·변경.
//   GET  /api/brand/rename            → 드라이런 리포트. 아무것도 바꾸지 않는다.
//   POST /api/brand/rename            → { brandId, newBrandId, confirm:"yes" } 로 실제 이름 변경.
//
// 배경: 신규 프로젝트의 seriesId 가 'projects<타임스탬프>' 로 만들어져 폴더명이 사람이 못 읽는
// 형태로 굳었다(예: projects1771052244218). 생성 쪽은 이름 기반 슬러그로 고쳤고, 이미 만들어진
// 폴더는 이 엔드포인트로 옮긴다.
//
// 안전 규칙:
//   · POST 도 confirm:"yes" 가 없으면 계획만 돌려준다(기본 드라이런).
//   · 복사(copy) 후 원본은 그대로 둔다. deleteOld:true 를 따로 줘야 지운다.
//   · 브랜드 레코드·프로젝트 레코드 안에 박힌 예전 경로(gs://…/brands/<old>/…)도 함께 고친다.
//     이걸 안 하면 폴더만 옮기고 캐릭터 시트 이미지가 전부 깨진다.
import { buildAiVideoUserRoot, buildAiVideoBrandPrefix, resolveUserId } from "../_shared/storage";
import { authorizeRequest } from "../_shared/auth.js";

type PagesFunction = (ctx: { request: Request; env: any }) => Promise<Response>;

const corsHeaders = (origin: string | null) => ({
  "Content-Type": "application/json; charset=utf-8",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization",
  "Access-Control-Allow-Origin": origin || "*",
  Vary: "Origin",
});
const send = (data: any, status = 200, origin: string | null = null) =>
  new Response(JSON.stringify(data, null, 2), { status, headers: corsHeaders(origin) });

export const onRequestOptions: PagesFunction = async ({ request }) =>
  new Response(null, { status: 204, headers: corsHeaders(request.headers.get("Origin")) });

/** 자동 생성된(사람이 못 읽는) id 판별 — projects<숫자> 또는 숫자만. */
function isAutoGeneratedId(id: string): boolean {
  return /^projects\d+$/i.test(id) || /^\d+$/.test(id);
}

/** 이름 → 폴더용 슬러그. GCS 경로가 ASCII만 허용하므로 영문/숫자/.-_ 만 남긴다. */
export function slugifyBrandId(title: string): string {
  return String(title || "")
    .trim()
    .toLowerCase()
    .replace(/[\s_]+/g, "-")
    .replace(/[^a-z0-9.-]+/g, "")
    .replace(/-{2,}/g, "-")
    .replace(/^[-.]+|[-.]+$/g, "")
    .slice(0, 40);
}

interface Ctx {
  bucket: string;
  basePrefix: string;
  userId: string;
  token: string;
  userProject: string;
}

export const onRequestGet: PagesFunction = async ({ request, env }) => {
  const origin = request.headers.get("Origin");
  try {
    const ctx = await buildCtx(request, env);
    if ("error" in ctx) return send({ error: ctx.error }, ctx.status, origin);

    const userRoot = buildAiVideoUserRoot(ctx.basePrefix, ctx.userId);
    const brandIds = await listChildFolders(ctx, `${userRoot}/brands/`);
    const projectIds = await listChildFolders(ctx, `${userRoot}/projects/`);

    // 프로젝트 레코드가 어떤 brandId/seriesId 를 참조하는지 미리 모아둔다(이름 변경 시 같이 고쳐야 함).
    const projectRefs: Record<string, string[]> = {};
    for (const projectId of projectIds.slice(0, 80)) {
      const rec = await readJson(ctx, `${userRoot}/projects/${projectId}/reference/data.json`);
      const payload = (rec && (rec.payload || rec)) || {};
      const refs = [payload.brandId, payload.seriesId, payload?.brandRef?.id]
        .map((v: any) => String(v || "").trim())
        .filter(Boolean);
      for (const ref of new Set(refs)) {
        if (!projectRefs[ref]) projectRefs[ref] = [];
        projectRefs[ref].push(projectId);
      }
    }

    const brands = [];
    for (const brandId of brandIds) {
      const rec = await readJson(ctx, `${buildAiVideoBrandPrefix(ctx.basePrefix, ctx.userId, brandId)}/reference/data.json`);
      const brandTitle = String(rec?.brandTitle || rec?.title || rec?.brandName || "").trim();
      const objects = await listObjects(ctx, `${buildAiVideoBrandPrefix(ctx.basePrefix, ctx.userId, brandId)}/`);
      const sheets = Array.isArray(rec?.characterSheets) ? rec.characterSheets : [];
      const suggestedId = slugifyBrandId(brandTitle);
      brands.push({
        brandId,
        brandTitle: brandTitle || "(이름 없음 — 브랜드 정의에 brandTitle 이 비어 있어요)",
        needsRename: isAutoGeneratedId(brandId),
        suggestedId: suggestedId && suggestedId !== brandId ? suggestedId : "",
        // 이름이 한글뿐이면 슬러그가 비어 사용자가 영문 이름을 직접 정해야 한다.
        suggestionNote: isAutoGeneratedId(brandId) && !suggestedId
          ? "이름에서 쓸 수 있는 영문/숫자가 없어요 — 새 영문 id를 직접 정해 주세요."
          : "",
        objectCount: objects.length,
        characterCount: sheets.length,
        characters: sheets.map((s: any) => String(s?.displayName || s?.token || "").replace(/^@+/, "")).filter(Boolean),
        referencingProjects: projectRefs[brandId] || [],
      });
    }

    return send({
      ok: true,
      dryRun: true,
      hint: "needsRename=true 인 항목의 새 영문 id 를 정해 POST /api/brand/rename {brandId, newBrandId, confirm:\"yes\"} 로 변경하세요. 원본은 남겨두고 복사합니다.",
      brands,
      projectCount: projectIds.length,
    }, 200, origin);
  } catch (e: any) {
    return send({ error: e?.message || "brand rename report failed" }, 500, origin);
  }
};

export const onRequestPost: PagesFunction = async ({ request, env }) => {
  const origin = request.headers.get("Origin");
  try {
    const ctx = await buildCtx(request, env);
    if ("error" in ctx) return send({ error: ctx.error }, ctx.status, origin);

    const body = await request.json().catch(() => ({} as any));
    const brandId = String(body?.brandId || "").trim();
    const newBrandId = String(body?.newBrandId || "").trim();
    const confirm = String(body?.confirm || "").trim().toLowerCase() === "yes";
    const deleteOld = body?.deleteOld === true;
    if (!brandId || !newBrandId) return send({ error: "brandId, newBrandId 필요" }, 400, origin);
    if (!/^[a-zA-Z0-9._-]+$/.test(newBrandId)) {
      return send({ error: "newBrandId 는 영문/숫자/._- 만 사용할 수 있어요(GCS 경로 제약)." }, 400, origin);
    }
    if (brandId === newBrandId) return send({ error: "같은 id 예요." }, 400, origin);

    const userRoot = buildAiVideoUserRoot(ctx.basePrefix, ctx.userId);
    const oldPrefix = buildAiVideoBrandPrefix(ctx.basePrefix, ctx.userId, brandId);
    const newPrefix = buildAiVideoBrandPrefix(ctx.basePrefix, ctx.userId, newBrandId);

    const sources = await listObjects(ctx, `${oldPrefix}/`);
    if (!sources.length) return send({ error: `${brandId} 폴더에 파일이 없어요(id를 다시 확인해 주세요).` }, 404, origin);
    const existing = await listObjects(ctx, `${newPrefix}/`);
    if (existing.length) return send({ error: `${newBrandId} 가 이미 있어요(파일 ${existing.length}개). 다른 id를 주세요.` }, 409, origin);

    // 이 브랜드를 참조하는 프로젝트 레코드도 같이 고친다.
    const projectIds = await listChildFolders(ctx, `${userRoot}/projects/`);
    const affectedProjects: string[] = [];
    for (const projectId of projectIds.slice(0, 80)) {
      const rec = await readJson(ctx, `${userRoot}/projects/${projectId}/reference/data.json`);
      if (!rec) continue;
      if (JSON.stringify(rec).includes(brandId)) affectedProjects.push(projectId);
    }

    const plan = {
      brandId,
      newBrandId,
      copyObjects: sources.length,
      rewriteBrandRecord: true,
      updateProjects: affectedProjects,
      deleteOld,
    };
    if (!confirm) {
      return send({ ok: true, dryRun: true, plan, hint: 'confirm:"yes" 를 함께 보내면 실제로 실행해요.' }, 200, origin);
    }

    // ① 파일 복사
    let copied = 0;
    for (const object of sources) {
      const target = newPrefix + object.slice(oldPrefix.length);
      await copyObject(ctx, object, target);
      copied++;
    }

    // ② 브랜드 레코드 안의 예전 경로·id 치환 (시트 이미지 gs:// 경로가 여기 박혀 있다)
    const brandRecordPath = `${newPrefix}/reference/data.json`;
    const brandRec = await readJson(ctx, brandRecordPath);
    if (brandRec) {
      const rewritten = JSON.parse(JSON.stringify(brandRec).split(oldPrefix).join(newPrefix));
      rewritten.brandId = newBrandId;
      await writeJson(ctx, brandRecordPath, rewritten);
    }

    // ③ 프로젝트 레코드의 brandId/seriesId/brandRef 및 경로 치환
    const updatedProjects: string[] = [];
    for (const projectId of affectedProjects) {
      const path = `${userRoot}/projects/${projectId}/reference/data.json`;
      const rec = await readJson(ctx, path);
      if (!rec) continue;
      const next = JSON.parse(JSON.stringify(rec).split(oldPrefix).join(newPrefix));
      const payload = next.payload || next;
      if (String(payload.brandId || "") === brandId) payload.brandId = newBrandId;
      if (String(payload.seriesId || "") === brandId) payload.seriesId = newBrandId;
      if (payload.brandRef && String(payload.brandRef.id || "") === brandId) payload.brandRef.id = newBrandId;
      await writeJson(ctx, path, next);
      updatedProjects.push(projectId);
    }

    // ④ 원본 정리는 기본적으로 하지 않는다(검증 후 deleteOld:true 로 별도 실행).
    let deleted = 0;
    if (deleteOld) {
      for (const object of sources) {
        await deleteObject(ctx, object);
        deleted++;
      }
    }

    return send({
      ok: true,
      dryRun: false,
      brandId,
      newBrandId,
      copied,
      updatedProjects,
      deletedOldObjects: deleted,
      note: deleteOld
        ? "원본 폴더를 삭제했어요."
        : `원본(${brandId})은 그대로 남겨뒀어요. 화면에서 확인한 뒤 deleteOld:true 로 정리하세요.`,
    }, 200, origin);
  } catch (e: any) {
    return send({ error: e?.message || "brand rename failed" }, 500, origin);
  }
};

// ───────── GCS 헬퍼 (이 저장소의 다른 엔드포인트와 동일한 자체 포함 방식) ─────────

async function buildCtx(request: Request, env: any): Promise<Ctx | { error: string; status: number }> {
  const auth = await authorizeRequest(request, env, { allowQueryToken: true });
  if (!auth.ok) return { error: auth.error, status: auth.status };
  const clientEmail = env.GOOGLE_CLIENT_EMAIL as string | undefined;
  const privateKeyRaw = env.GOOGLE_PRIVATE_KEY as string | undefined;
  const baseOutput = env.VIDEO_OUTPUT_GCS_URI as string | undefined;
  if (!clientEmail || !privateKeyRaw || !baseOutput) {
    return { error: "Missing GOOGLE_CLIENT_EMAIL/GOOGLE_PRIVATE_KEY/VIDEO_OUTPUT_GCS_URI", status: 500 };
  }
  const parsed = parseGcsUri(baseOutput);
  if (!parsed) return { error: "Invalid VIDEO_OUTPUT_GCS_URI", status: 500 };
  const token = await getGoogleAccessToken({
    clientEmail,
    privateKeyPem: privateKeyRaw,
    scope: "https://www.googleapis.com/auth/cloud-platform",
  });
  return {
    bucket: parsed.bucket,
    basePrefix: parsed.object.replace(/\/$/, ""),
    userId: resolveUserId(auth.userId, env),
    token,
    userProject: String(env.GCS_BILLING_PROJECT_ID || env.GOOGLE_PROJECT_ID || ""),
  };
}

function gcsHeaders(ctx: Ctx, extra: Record<string, string> = {}) {
  return {
    Authorization: `Bearer ${ctx.token}`,
    ...(ctx.userProject ? { "X-Goog-User-Project": ctx.userProject } : {}),
    ...extra,
  };
}

/** prefix 직속 하위 폴더 이름 목록 (delimiter 로 prefixes 만 받는다). */
async function listChildFolders(ctx: Ctx, prefix: string): Promise<string[]> {
  const url = `https://storage.googleapis.com/storage/v1/b/${encodeURIComponent(ctx.bucket)}/o?prefix=${encodeURIComponent(prefix)}&delimiter=%2F&maxResults=500${ctx.userProject ? `&userProject=${encodeURIComponent(ctx.userProject)}` : ""}`;
  const res = await fetch(url, { headers: gcsHeaders(ctx) });
  if (!res.ok) return [];
  const json = await res.json().catch(() => ({} as any));
  const prefixes: string[] = Array.isArray((json as any)?.prefixes) ? (json as any).prefixes : [];
  return prefixes
    .map((p) => p.slice(prefix.length).replace(/\/$/, ""))
    .filter((v) => !!v);
}

async function listObjects(ctx: Ctx, prefix: string): Promise<string[]> {
  const out: string[] = [];
  let pageToken = "";
  for (let i = 0; i < 20; i++) {
    const url = `https://storage.googleapis.com/storage/v1/b/${encodeURIComponent(ctx.bucket)}/o?prefix=${encodeURIComponent(prefix)}&maxResults=1000${pageToken ? `&pageToken=${encodeURIComponent(pageToken)}` : ""}${ctx.userProject ? `&userProject=${encodeURIComponent(ctx.userProject)}` : ""}`;
    const res = await fetch(url, { headers: gcsHeaders(ctx) });
    if (!res.ok) break;
    const json: any = await res.json().catch(() => ({}));
    for (const item of Array.isArray(json?.items) ? json.items : []) {
      const name = String(item?.name || "");
      if (name) out.push(name);
    }
    pageToken = String(json?.nextPageToken || "");
    if (!pageToken) break;
  }
  return out;
}

async function readJson(ctx: Ctx, object: string): Promise<any | null> {
  const url = `https://storage.googleapis.com/storage/v1/b/${encodeURIComponent(ctx.bucket)}/o/${encodeURIComponent(object)}?alt=media${ctx.userProject ? `&userProject=${encodeURIComponent(ctx.userProject)}` : ""}`;
  const res = await fetch(url, { headers: gcsHeaders(ctx) });
  if (!res.ok) return null;
  const text = await res.text();
  try { return JSON.parse(text); } catch { return null; }
}

async function writeJson(ctx: Ctx, object: string, data: any): Promise<void> {
  const url = `https://storage.googleapis.com/upload/storage/v1/b/${encodeURIComponent(ctx.bucket)}/o?uploadType=media&name=${encodeURIComponent(object)}${ctx.userProject ? `&userProject=${encodeURIComponent(ctx.userProject)}` : ""}`;
  const res = await fetch(url, {
    method: "POST",
    headers: gcsHeaders(ctx, { "Content-Type": "application/json; charset=utf-8" }),
    body: JSON.stringify(data),
  });
  if (!res.ok) throw new Error(`write failed (${res.status}): ${object}`);
}

async function copyObject(ctx: Ctx, source: string, target: string): Promise<void> {
  const url = `https://storage.googleapis.com/storage/v1/b/${encodeURIComponent(ctx.bucket)}/o/${encodeURIComponent(source)}/copyTo/b/${encodeURIComponent(ctx.bucket)}/o/${encodeURIComponent(target)}${ctx.userProject ? `?userProject=${encodeURIComponent(ctx.userProject)}` : ""}`;
  const res = await fetch(url, { method: "POST", headers: gcsHeaders(ctx, { "Content-Length": "0" }) });
  if (!res.ok) {
    const detail = await res.text().catch(() => "");
    throw new Error(`copy failed (${res.status}): ${source} → ${target} ${detail.slice(0, 200)}`);
  }
}

async function deleteObject(ctx: Ctx, object: string): Promise<void> {
  const url = `https://storage.googleapis.com/storage/v1/b/${encodeURIComponent(ctx.bucket)}/o/${encodeURIComponent(object)}${ctx.userProject ? `?userProject=${encodeURIComponent(ctx.userProject)}` : ""}`;
  const res = await fetch(url, { method: "DELETE", headers: gcsHeaders(ctx) });
  if (!res.ok && res.status !== 404) throw new Error(`delete failed (${res.status}): ${object}`);
}

function parseGcsUri(uri: string): { bucket: string; object: string } | null {
  if (!uri.startsWith("gs://")) return null;
  const rest = uri.slice(5);
  const slash = rest.indexOf("/");
  if (slash === -1) return null;
  return { bucket: rest.slice(0, slash), object: rest.slice(slash + 1) };
}

async function getGoogleAccessToken(opts: { clientEmail: string; privateKeyPem: string; scope: string }) {
  const now = Math.floor(Date.now() / 1000);
  const aud = "https://oauth2.googleapis.com/token";
  const header = { alg: "RS256", typ: "JWT" };
  const claimSet = { iss: opts.clientEmail, scope: opts.scope, aud, iat: now, exp: now + 3600 };
  const jwtUnsigned = `${base64url(JSON.stringify(header))}.${base64url(JSON.stringify(claimSet))}`;
  const signature = await signRS256(jwtUnsigned, opts.privateKeyPem);
  const form = new URLSearchParams();
  form.set("grant_type", "urn:ietf:params:oauth:grant-type:jwt-bearer");
  form.set("assertion", `${jwtUnsigned}.${signature}`);
  const res = await fetch(aud, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: form.toString(),
  });
  const text = await res.text();
  if (!res.ok) throw new Error(`OAuth token error (${res.status}): ${text}`);
  const json = JSON.parse(text);
  if (!json.access_token) throw new Error("No access_token in OAuth response");
  return json.access_token as string;
}

function base64url(input: string) {
  return btoa(unescape(encodeURIComponent(input))).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

async function signRS256(data: string, privateKeyPem: string) {
  const pem = privateKeyPem.replace(/\\n/g, "\n");
  const body = pem.replace(/-----BEGIN PRIVATE KEY-----/, "").replace(/-----END PRIVATE KEY-----/, "").replace(/\s+/g, "");
  const raw = atob(body);
  const bytes = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);
  const key = await crypto.subtle.importKey("pkcs8", bytes, { name: "RSASSA-PKCS1-v1_5", hash: "SHA-256" }, false, ["sign"]);
  const sig = await crypto.subtle.sign("RSASSA-PKCS1-v1_5", key, new TextEncoder().encode(data));
  let out = "";
  new Uint8Array(sig).forEach((b) => { out += String.fromCharCode(b); });
  return btoa(out).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}
